### ISSUE TITLE
compile not pass

### ISSUE THREAD

**Issue by jianghong-023** [bootlin/libva-v4l2-request#2]
Hi there:
   I`am on the sunxi h5 board to compile libve-v4l2-request can not pass ,
  used libvb : https://github.com/01org/libva ,also used the inter libva 2.1.0 :

kernel:
 Repository: https://github.com/bootlin/linux-cedrus
 Branch: cedrus/4.18/vpu-support-merge

Error info:
 request.c: In function ‘__vaDriverInit_0_39’:
request.c:93:8: error: ‘struct VADriverVTable’ has no member named ‘vaExportSurfaceHandle’
  vtable->vaExportSurfaceHandle = RequestExportSurfaceHandle;

  please help me ! Thanks

**Comment by Grandebestia** [comment]
Hi!
I had the same issue (same kernel repository & branch, same error), and I fixed with the same repository of libva https://github.com/intel/libva (branch: master).
Maybe there's something wrong with your headers configuration?
TBH I'm using an H3 board with Armbian 5.38 (Debian stretch next 4.14.14)

**Comment by paulkocialkowski** [comment]
Should be fixed now, thanks!
